version: '3'
services:
  n1:
    build: 
      context: .
      args: 
        seed: 1
        peed_id: 12D3KooWHHzSeKaY8xuZVzkLbKFfvNgPPeKhFBGrMbNzbm5akpqu
    ports:
      - "9001:9000"
      - "8999:8999"
    networks:
      local_net:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10
        
  n2:
    depends_on: 
      - n1
    build: 
      context: .
      args: 
        seed: 2
        peed_id: 12D3KooWKRyzVWW6ChFjQjK4miCty85Niy49tpPV95XdKu1BcvMA
        addnode: "-j /ip4/172.16.238.10/tcp/9000/ipfs/12D3KooWHHzSeKaY8xuZVzkLbKFfvNgPPeKhFBGrMbNzbm5akpqu"
    ports:
      - "9002:9000"
      - "8998:8999"
    networks:
      local_net:
        ipv4_address: 172.16.238.11
        ipv6_address: 2001:3984:3989::11
        
  # n3:
  #   depends_on: 
  #     - n2
  #   build: 
  #     context: .
  #     args: 
  #       seed: 3
  #       peed_id: 12D3KooWB1b3qZxWJanuhtseF3DmPggHCtG36KZ9ixkqHtdKH9fh
  #       addnode: "-j /ip4/172.16.238.11/tcp/9000/ipfs/12D3KooWKRyzVWW6ChFjQjK4miCty85Niy49tpPV95XdKu1BcvMA"
  #   ports:
  #     - "9003:9000"
  #   networks:
  #     local_net:
  #       ipv4_address: 172.16.238.12
  #       ipv6_address: 2001:3984:3989::12
        
  # n4:
  #   depends_on: 
  #     - n3
  #   build: 
  #     context: .
  #     args: 
  #       seed: 4
  #       peed_id: 12D3KooWE4qDcRrueTuRYWUdQZgcy7APZqBngVeXRt4Y6ytHizKV
  #       addnode: "-j /ip4/172.16.238.10/tcp/9000/ipfs/12D3KooWHHzSeKaY8xuZVzkLbKFfvNgPPeKhFBGrMbNzbm5akpqu"
  #   ports:
  #     - "9004:9000"
  #   networks:
  #     local_net:
  #       ipv4_address: 172.16.238.13
  #       ipv6_address: 2001:3984:3989::13
        
  
  # n5:
  #   depends_on: 
  #     - n4
  #   build: 
  #     context: .
  #     args: 
  #       seed: 5
  #       peed_id: 12D3KooWPgam4TzSVCRa4AbhxQnM9abCYR4E9hV57SN7eAjEYn1j
  #       addnode: "-j /ip4/172.16.238.10/tcp/9000/ipfs/12D3KooWHHzSeKaY8xuZVzkLbKFfvNgPPeKhFBGrMbNzbm5akpqu"
  #   ports:
  #     - "9005:9000"
  #   networks:
  #     local_net:
  #       ipv4_address: 172.16.238.14
  #       ipv6_address: 2001:3984:3989::14
        
  
networks:
  local_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24
      -
        subnet: 2001:3984:3989::/64