test:
	cd blockchain && go test -v ./...
	cd blockcode && go test -v ./...
	cd accountmgr && go test -v ./...
	cd config && go test -v ./...
	cd crypto && go test -v ./...
	cd elldb && go test -v ./...
	cd miner && go test -v ./...
	cd node && go test -v ./...
	cd rpc && go test -v ./...
	cd txpool && go test -v ./...
	cd util && go test -v ./...
	cd types && go test -v ./...
	
clean: 
	go vet ./... && gofmt -s -w .
	
release:
	bash release.sh